=== gunalmel/spring-security-example/src/test/resources/DbUnitDataSets/testDb.dtd
<!ELEMENT dataset (
   (ORGANIZATION|
    ROLE|
    USER_ACCOUNT|
    USER_DETAILS|
    USER_ORGANIZATION|
    USER_ROLE)*)>

<!ELEMENT ORGANIZATION EMPTY>
<!ATTLIST ORGANIZATION
    ID CDATA #REQUIRED
    UNIQUE_NAME CDATA #REQUIRED
    NAME CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT ROLE EMPTY>
<!ATTLIST ROLE
    ID CDATA #REQUIRED
    ROLE_NAME CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT USER_ACCOUNT EMPTY>
<!ATTLIST USER_ACCOUNT
    ID CDATA #REQUIRED
    USER_NAME CDATA #REQUIRED
    EMAIL CDATA #IMPLIED
    PASSWORD_SALT CDATA #REQUIRED
    PASSWORD CDATA #REQUIRED
    PASSWORD_QUESTION CDATA #REQUIRED
    PASSWORD_ANSWER CDATA #REQUIRED
    ENABLED CDATA #REQUIRED
    LOCKED CDATA #REQUIRED
    LAST_LOCK_OUT_DATE CDATA #IMPLIED
    CREATED_DATE CDATA #REQUIRED
    LAST_LOGIN_DATE CDATA #REQUIRED
    LAST_PASSWORD_CHANGED_DATE CDATA #REQUIRED
    FAILED_PWD_WIN_START CDATA #IMPLIED
    FAILED_PWD_ANSWER_WIN_START CDATA #IMPLIED
    COMMENTS CDATA #IMPLIED
>

<!ELEMENT USER_DETAILS EMPTY>
<!ATTLIST USER_DETAILS
    USER_ID CDATA #REQUIRED
    LAST_NAME CDATA #REQUIRED
    FIRST_NAME CDATA #REQUIRED
    MIDDLE_NAME CDATA #IMPLIED
    EMPLOYEE_ID CDATA #REQUIRED
    UNIQUE_NAME CDATA #IMPLIED
    INSTITUTION_NAME CDATA #REQUIRED
    DEPARTMENT_NAME CDATA #IMPLIED
    PHONE CDATA #IMPLIED
    PAGER CDATA #IMPLIED
>

<!ELEMENT USER_ORGANIZATION EMPTY>
<!ATTLIST USER_ORGANIZATION
    ID CDATA #REQUIRED
    USER_ID CDATA #REQUIRED
    ORGANIZATION_ID CDATA #REQUIRED
    APPROVED CDATA #REQUIRED
>

<!ELEMENT USER_ROLE EMPTY>
<!ATTLIST USER_ROLE
    USER_ID CDATA #REQUIRED
    ROLE_ID CDATA #REQUIRED
>

=== gunalmel/spring-security-example/src/test/resources/DbUnitDataSets/testDbFull.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "testDb.dtd">
<dataset>
  <ROLE ID="0" ROLE_NAME="Administrator" DESCRIPTION="Application administrator who has unlimited privileges within the application domain. User would be responsible for maintaining and setting up the application. Staff from and IT help desk support would be an ideal candidate"/>
  <ROLE ID="1" ROLE_NAME="Organization_Admin" DESCRIPTION="Administrator user for a given organization. This user is a power user capable of maintaining user access privileges for the given organization. This user can also post announcements and upload cheat sheet for the given organization"/>
  <ROLE ID="2" ROLE_NAME="Organization_Scheduler" DESCRIPTION="User for a given organization who can process"/>
  <ROLE ID="3" ROLE_NAME="External_Scheduler" DESCRIPTION="A study team member who can submit/update,cancel scheduling requests. The user can also access/update all scheduling requests for the study protocol the user is affiliated with. Protocol Access List would have affiliation information"/>
  <USER_ACCOUNT ID="0" USER_NAME="administrator" EMAIL="gunalmel@med.umich.edu" PASSWORD_SALT="01dc8f8613aefe48" PASSWORD="408fb42b266374568db95f071c3e26cdb5963d811dab8d01879fdbf8353b8dac" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="223b1dbfb8240a3c30aa1c60b05be1cc19e979d4ccdc20aeb6ee8a3c3a295b7a" ENABLED="true" LOCKED="false" LAST_LOCK_OUT_DATE="0001-01-01 12:00:00.0" CREATED_DATE="2011-10-26 13:41:51.906" LAST_LOGIN_DATE="2011-10-26 13:41:51.906" LAST_PASSWORD_CHANGED_DATE="2011-10-26 13:41:51.906" FAILED_PWD_WIN_START="0001-01-01 12:00:00.0" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Built-in administrator account."/>
  <USER_ACCOUNT ID="1" USER_NAME="gunalmel" EMAIL="gunalmel@yahoo.com" PASSWORD_SALT="29d14dc9c10785bd" PASSWORD="9ac55e8b87fdb3ea13c179fe8b2177ccdb12e19a29943ca7bd0cca8d4af1f126" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="0189aa9169f5be91651df11f7c8da582053753c3868c38eaac24f60c7c56135f" ENABLED="true" LOCKED="false" LAST_LOCK_OUT_DATE="0001-01-01 12:00:00.0" CREATED_DATE="2011-10-26 13:41:51.921" LAST_LOGIN_DATE="2011-10-26 13:41:51.921" LAST_PASSWORD_CHANGED_DATE="2011-10-26 13:41:51.921" FAILED_PWD_WIN_START="0001-01-01 12:00:00.0" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Developer account created for testing purposes in thee Organization_Admin role. Enabled, not locked"/>
  <USER_ACCOUNT ID="2" USER_NAME="test_org_admin" EMAIL="test_org_admin@yahoo.com" PASSWORD_SALT="7f156c99518ca873" PASSWORD="036097b600ff90a0bc80480d3e3c460ae66453049b8a3e123742cb6b986a34a7" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="dc6da63f3898fc58e2beaf97896666945c51de823759ff745fe9669147f2aad3" ENABLED="true" LOCKED="false" LAST_LOCK_OUT_DATE="0001-01-01 12:00:00.0" CREATED_DATE="2011-10-26 13:41:51.937" LAST_LOGIN_DATE="2011-10-26 13:41:51.937" LAST_PASSWORD_CHANGED_DATE="2011-10-26 13:41:51.937" FAILED_PWD_WIN_START="0001-01-01 12:00:00.0" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Test user account in Organization_Admin role. Enabled, not locked"/>
  <USER_ACCOUNT ID="3" USER_NAME="test_org_sch" EMAIL="test_org_sch@yahoo.com" PASSWORD_SALT="6c2d5fc5ef295352" PASSWORD="b4419ff8d804502a0dd493eabb21ce87a3f96a817f3edfe770e0731413b1d12d" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="95b0f5f60d6b07c9603f5687f6535ae5b4d1cf185d2cbf6b42abbf99dd308c73" ENABLED="true" LOCKED="false" LAST_LOCK_OUT_DATE="0001-01-01 12:00:00.0" CREATED_DATE="2011-10-26 13:41:51.937" LAST_LOGIN_DATE="2011-10-26 13:41:51.937" LAST_PASSWORD_CHANGED_DATE="2011-10-26 13:41:51.937" FAILED_PWD_WIN_START="0001-01-01 12:00:00.0" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Test user account in Organization_Scheduler role. Enabled, not locked"/>
  <USER_ACCOUNT ID="4" USER_NAME="test_scheduler" EMAIL="test_scheduler@yahoo.com" PASSWORD_SALT="a683e58ca44ef47b" PASSWORD="a0e2d830003a0e0145a3b586a9f4cafc79e9b853d943bfff9cbc1283679ee0b8" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="a21093ecc5e228c9eab15560ccb6cae870e57699377ec9c7aae609e07b8e143b" ENABLED="true" LOCKED="false" LAST_LOCK_OUT_DATE="0001-01-01 12:00:00.0" CREATED_DATE="2011-10-26 13:41:51.937" LAST_LOGIN_DATE="2011-10-26 13:41:51.937" LAST_PASSWORD_CHANGED_DATE="2011-10-26 13:41:51.937" FAILED_PWD_WIN_START="0001-01-01 12:00:00.0" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Test user account in External_Scheduler role. Enabled, not locked"/>
  <USER_ACCOUNT ID="5" USER_NAME="test_disabled" EMAIL="test_disabled@yahoo.com" PASSWORD_SALT="4bb90ae09ffc0e3f" PASSWORD="d67e5086ed9f2f06d79cb7f647c8e37dbc97e92820d5eafd2fc60d104d31970c" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="ebc96a609d57a9d437f6013361028bc382c243b576155653ec9b7b5781f744c5" ENABLED="false" LOCKED="false" LAST_LOCK_OUT_DATE="0001-01-01 12:00:00.0" CREATED_DATE="2011-10-26 13:41:51.937" LAST_LOGIN_DATE="2011-10-26 13:41:51.937" LAST_PASSWORD_CHANGED_DATE="2011-10-26 13:41:51.937" FAILED_PWD_WIN_START="0001-01-01 12:00:00.0" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Test user account in Organization_Scheduler role. Not approved (disabled), not locked"/>
  <USER_ACCOUNT ID="6" USER_NAME="test_locked" EMAIL="test_locked@yahoo.com" PASSWORD_SALT="a90ef54b2d0c2891" PASSWORD="01e813120ca098563057302f82b85f1e4c1dd8b5c7417eef5371f9709d5ec199" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="721cf5f7e574644c5cc4cac6d61b91c43ce2cf898c4e09eaff080881357b1140" ENABLED="true" LOCKED="true" LAST_LOCK_OUT_DATE="2011-10-26 13:41:51.937" CREATED_DATE="2007-10-26 13:41:51.937" LAST_LOGIN_DATE="2011-10-26 13:41:51.937" LAST_PASSWORD_CHANGED_DATE="2011-07-18 13:41:51.937" FAILED_PWD_WIN_START="2011-10-26 13:41:51.937" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Test user account in External_Scheduler role. Disabled because it is locked, locked"/>
  <USER_ACCOUNT ID="7" USER_NAME="test_acc_expired" EMAIL="test_acc_expired@yahoo.com" PASSWORD_SALT="9197c151a95cba91" PASSWORD="d8cfb60321aff4dfbfc8fb0fa48bfa68cda16666d3c86c058b7a85762af38f57" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="26bbd1241268ad46674ce7b153dda636bb46f96d170fc3cd56caa1184d75d6fb" ENABLED="true" LOCKED="false" LAST_LOCK_OUT_DATE="0001-01-01 12:00:00.0" CREATED_DATE="2007-10-26 13:41:51.937" LAST_LOGIN_DATE="2010-09-21 13:41:51.937" LAST_PASSWORD_CHANGED_DATE="2011-07-18 13:41:51.937" FAILED_PWD_WIN_START="0001-01-01 12:00:00.0" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Test user account in External_Scheduler role. Account (disabled) has expired because the last login date is 400 days before current date. (Inactivity grace period is 1 yr.)"/>
  <USER_ACCOUNT ID="8" USER_NAME="test_pwd_expired" EMAIL="test_pwd_expired@yahoo.com" PASSWORD_SALT="3319650a536fc013" PASSWORD="1881e9cfeb432e08bea68077b9168d516a2faf59a7be23c063fd35bead6d9929" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="5a34ffa0d88b8354f6b6aae04159614016df1fdf0af56c8f023c8342e95e5431" ENABLED="true" LOCKED="false" LAST_LOCK_OUT_DATE="0001-01-01 12:00:00.0" CREATED_DATE="2007-10-26 13:41:51.953" LAST_LOGIN_DATE="2011-07-18 13:41:51.953" LAST_PASSWORD_CHANGED_DATE="2010-09-21 13:41:51.953" FAILED_PWD_WIN_START="0001-01-01 12:00:00.0" FAILED_PWD_ANSWER_WIN_START="0001-01-01 00:00:00.0" COMMENTS="Test user account in External_Scheduler role. Password has expired and the user needs to reset it when the user logs in with the old password for the first time after pwd has expired.)"/>
  <USER_ACCOUNT ID="9" USER_NAME="test_pwdans_locked" EMAIL="test_pwdans_locked@yahoo.com" PASSWORD_SALT="357f1034f68b4107" PASSWORD="b6906bb76be4516143af0c7e2e7a50df8f67a31b0ee36d82b0da9bb36a351e2b" PASSWORD_QUESTION="For which organization are you working for?" PASSWORD_ANSWER="22bf9aaf79f9db5e06ad731d95c44e392dbfdd7e5f61a40ec15a41975ca8652c" ENABLED="true" LOCKED="true" LAST_LOCK_OUT_DATE="2011-10-26 13:41:51.953" CREATED_DATE="2007-10-26 13:41:51.953" LAST_LOGIN_DATE="2011-07-18 13:41:51.953" LAST_PASSWORD_CHANGED_DATE="2011-07-18 13:41:51.953" FAILED_PWD_WIN_START="0001-01-01 00:00:00.0" FAILED_PWD_ANSWER_WIN_START="2011-10-26 13:41:51.953" COMMENTS="Test user account in External_Scheduler role. Password has expired and the user needs to reset it when the user logs in with the old password for the first time after pwd has expired.)"/>
  <USER_DETAILS USER_ID="0" LAST_NAME="Gunal" FIRST_NAME="Melih" MIDDLE_NAME="" EMPLOYEE_ID="71389619" UNIQUE_NAME="gunalmel" INSTITUTION_NAME="University of Michigan" DEPARTMENT_NAME="MICHR" PHONE="7349986145" PAGER="N/A"/>
  <USER_DETAILS USER_ID="1" LAST_NAME="Gunal" FIRST_NAME="Melih" MIDDLE_NAME="" EMPLOYEE_ID="71389619" UNIQUE_NAME="gunalmel" INSTITUTION_NAME="University of Michigan" DEPARTMENT_NAME="MICHR" PHONE="7349986145" PAGER="N/A"/>
  <USER_DETAILS USER_ID="2" LAST_NAME="Gunal" FIRST_NAME="Melih" MIDDLE_NAME="" EMPLOYEE_ID="71389619" UNIQUE_NAME="gunalmel" INSTITUTION_NAME="University of Michigan" DEPARTMENT_NAME="MICHR" PHONE="7349986145" PAGER="N/A"/>
  <USER_DETAILS USER_ID="3" LAST_NAME="Gunal" FIRST_NAME="Melih" MIDDLE_NAME="" EMPLOYEE_ID="71389619" UNIQUE_NAME="gunalmel" INSTITUTION_NAME="University of Michigan" DEPARTMENT_NAME="MICHR" PHONE="7349986145" PAGER="N/A"/>
  <USER_DETAILS USER_ID="4" LAST_NAME="Gunal" FIRST_NAME="Melih" MIDDLE_NAME="" EMPLOYEE_ID="71389619" UNIQUE_NAME="gunalmel" INSTITUTION_NAME="University of Michigan" DEPARTMENT_NAME="MICHR" PHONE="7349986145" PAGER="N/A"/>
